import { createHash } from "node:crypto";

const publicUrl = (file) => `/${String(file).replace(/^public\//, "")}`;

export function buildArtworkRuntimePackData(manifest) {
  const assets = {};
  const packs = {};
  for (const asset of manifest.assets || []) {
    if (!["runtime-ready", "integrated", "verified"].includes(asset.productionStatus)) continue;
    assets[asset.semanticId] = {
      source: { kind: "file", file: publicUrl(asset.expectedFilenames.runtime), format: asset.output.format },
      technical: {
        width: asset.output.canvas.width,
        height: asset.output.canvas.height,
        alpha: asset.output.alpha,
        pixelArt: asset.output.pixelArt,
        smoothing: asset.output.smoothing,
        trimFrames: asset.output.trimFrames,
        nativePixelsPerLogicalUnit: asset.masterScale.nativePixelsPerLogicalUnit,
        ...(asset.output.spriteSheet ? {
          frameWidth: asset.output.spriteSheet.frameWidth,
          frameHeight: asset.output.spriteSheet.frameHeight,
          rows: asset.output.spriteSheet.rows,
          columns: asset.output.spriteSheet.columns,
          frameOrder: asset.output.spriteSheet.frameOrder,
        } : {}),
      },
      workflow: { status: asset.workflow.currentStatus, version: asset.version },
      provenance: {
        originType: asset.provenance.originType,
        specificationVersion: asset.provenance.specificationVersion,
        assetVersion: asset.provenance.assetVersion,
        sourceSha256: asset.provenance.sourceSha256,
      },
    };
    const pack = packs[asset.scenePackId] || { id: asset.scenePackId, sceneIds: [], assetIds: [] };
    pack.sceneIds = [...new Set([...pack.sceneIds, ...asset.intendedScenes])].sort();
    pack.assetIds = [...new Set([...pack.assetIds, asset.semanticId])].sort();
    packs[asset.scenePackId] = pack;
  }
  return {
    schemaVersion: manifest.schemaVersion,
    sourceManifestId: manifest.id,
    sourceRevision: manifest.revision,
    sourceSha256: createHash("sha256").update(JSON.stringify(manifest)).digest("hex"),
    assets,
    packs,
  };
}

export function renderArtworkRuntimePackModule(manifest) {
  const data = buildArtworkRuntimePackData(manifest);
  return `// Generated by scripts/generate-artwork-runtime-packs.mjs. Do not edit by hand.\n`
    + `export const ARTWORK_RUNTIME_PACK_SCHEMA_VERSION = ${data.schemaVersion};\n`
    + `export const ARTWORK_RUNTIME_PACK_PROVENANCE = Object.freeze(${JSON.stringify({ sourceManifestId: data.sourceManifestId, sourceRevision: data.sourceRevision, sourceSha256: data.sourceSha256 }, null, 2)});\n`
    + `export const ARTWORK_RUNTIME_ASSETS = Object.freeze(${JSON.stringify(data.assets, null, 2)});\n`
    + `export const ARTWORK_RUNTIME_PACKS = Object.freeze(${JSON.stringify(data.packs, null, 2)});\n`;
}
