const jsonBlock = (value) => `\`\`\`json\n${JSON.stringify(value, null, 2)}\n\`\`\``;

export function renderPhase8APackageJson(packageDefinition) {
  return `${JSON.stringify(packageDefinition, null, 2)}\n`;
}

export function renderPhase8ARuntimeModule(packageDefinition) {
  const familyShadows = new Map(packageDefinition.familyContracts.map(({ id, shadowRule }) => [id, shadowRule]));
  const input = {
    assets: packageDefinition.assets.map((asset) => ({
      id: asset.semanticId,
      family: asset.familyId,
      prefabId: asset.prefabId,
      stateMapId: asset.stateMapId,
      file: asset.expectedFilenames.runtime,
      width: asset.output.canvas.width,
      height: asset.output.canvas.height,
      alpha: asset.output.alpha,
      frameWidth: asset.output.spriteSheet?.frameWidth || null,
      frameHeight: asset.output.spriteSheet?.frameHeight || null,
      directions: asset.directions,
      states: asset.states,
      layers: asset.layers.map(({ id }) => id),
      origin: asset.anchor.normalized,
      shadow: familyShadows.get(asset.familyId),
      geometry: asset.geometry,
      sockets: Object.fromEntries(asset.sockets.map((socket) => [socket.id, socket.logical])),
      animations: asset.animations,
      scenes: asset.intendedScenes,
      // Retain the declarative binding metadata needed by the normal scene
      // runtime. Earlier output kept only x/y and silently discarded repeat,
      // state, responsive, and dynamic-owner bindings.
      placements: asset.scenePlacement.map(({ instanceId, ...placement }) => ({ id: instanceId, ...placement })),
    })),
  };
  return `// Generated by scripts/export-phase8a-production-package.mjs. Do not hand-edit.\nimport { buildPhase8ARuntimeDefinitions } from "../verticalSlice/phase8aRuntimeBuilder.js";\nexport const PHASE_8A_RUNTIME_DEFINITIONS = buildPhase8ARuntimeDefinitions(${JSON.stringify(input)});\n`;
}

export function renderPhase8APromptBook(packageDefinition) {
  const sections = packageDefinition.assets.map((asset, index) => {
    const sheet = asset.output.spriteSheet
      ? `${asset.output.spriteSheet.columns}×${asset.output.spriteSheet.rows}; ${asset.output.spriteSheet.frameCount} frames; ${asset.output.spriteSheet.frameWidth}×${asset.output.spriteSheet.frameHeight}px each; order: ${asset.output.spriteSheet.frameOrder.join(", ")}`
      : "single untrimmed image";
    return `## ${String(index + 1).padStart(2, "0")} — ${asset.semanticId}

- Family: \`${asset.familyId}\`
- Purpose: ${asset.gameplayPurpose}
- Output: \`${asset.output.canvas.width}×${asset.output.canvas.height}\` ${asset.output.format.toUpperCase()}, alpha=${asset.output.alpha}; ${sheet}
- Logical display: \`${asset.masterScale.logicalDisplay.width}×${asset.masterScale.logicalDisplay.height}\`
- Camera: ${asset.camera.projection}
- Anchor: ${asset.anchor.name} at \`${asset.anchor.normalized.x}, ${asset.anchor.normalized.y}\`
- States: ${asset.states.join(", ")}
- Layers: ${asset.layers.map(({ id }) => id).join(", ")}
- Directions: ${asset.directions.join(", ") || "none"}
- Runtime filename: \`${asset.expectedFilenames.runtime}\`
- Prefab/state: \`${asset.prefabId}\` / \`${asset.stateMapId}\`
- Scene destination: ${asset.scenePlacement.map(({ sceneId, layoutId, instanceId }) => `\`${sceneId}\` → \`${layoutId}\` → \`${instanceId}\``).join("; ")}
- Fallback: ${asset.placeholder.development}; ${asset.placeholder.production}

### Generator prompt

${asset.promptPackage.positivePrompt}

### Negative prompt / forbidden output

${asset.promptPackage.negativePrompt}

### Delivery

${asset.promptPackage.deliveryInstruction}

### Geometry and sockets

${jsonBlock({ geometry: asset.geometry, sockets: asset.sockets })}

### Automated validation

${asset.validation.checklist.map((item) => `- ${item}`).join("\n")}
`;
  });
  return `# KindWorks Phase 8A Generator-Ready Prompt Book

Generated from \`${packageDefinition.id}\` revision ${packageDefinition.revision}. This is a production specification, not permission to mass-generate or integrate artwork. Generate and review one dependency wave at a time.

${sections.join("\n")}`;
}

export function renderPhase8ADependencyOrder(packageDefinition) {
  const byId = new Map(packageDefinition.assets.map((asset) => [asset.semanticId, asset]));
  return `# KindWorks Phase 8A Dependency-Ordered Production List

Foundational assets must be approved before dependent variants. A failed wave returns to revision without advancing later waves.

${packageDefinition.dependencyOrder.map(({ wave, name, assetIds }) => `## Wave ${wave} — ${name}

${assetIds.map((id) => {
    const asset = byId.get(id);
    return `- \`${id}\` → \`${asset.expectedFilenames.runtime}\` (depends on: ${asset.dependencies.map((dependency) => `\`${dependency}\``).join(", ") || "none"})`;
  }).join("\n")}`).join("\n\n")}

## Approval sequence

1. Validate exact file, alpha, dimensions, grid, and frame order in staging.
2. Review native size and intended gameplay size in Asset Lab.
3. Check anchor, sockets, geometry overlays, state alignment, directions, animation, and occlusion.
4. Approve the wave; copy approved masters to the runtime export step.
5. Change central semantic registry metadata only. Do not edit gameplay scenes per asset.
6. Run Phase 8A, visual registry, regression, build, and screenshot checks before the next wave.
`;
}
